### ISSUE TITLE
LUT error in `inverse_scale` when `mask_detail=True`

### ISSUE THREAD

**Issue by cN3rd** [Irrational-Encoding-Wizardry/kagefunc#1]
`inverse_scale(..., mask_detail=True)` calls a function called `generate_mask`, that does LUTing, which is supported in up to 16bit integer.

In the current implementation, the source clip is upsampled to 32bit float, and is passed as-is to `generate_mask`, generating the error.

a possible fix would be downsampling `source` to 16bit integer in the `generate_mask` call, and/or upsampling the result mask to 32bit float so the original 32bit float sampling of both the source and the descaled clip could be preserved.

**Comment by BluBb-mADe** [comment]
It probably would be easier to just make the mask_detail function 32bit float aware. All dependencies should support 32bit float already.

**Comment by kageru** [comment]
`std.Lut` doesn't work in float, so I'll either have to re-implement it using `std.Expr` (which could be difficult or slow due to the lack of bitwise operators) or just generate the mask in 16 bit and then convert that to float.
`mask_detail` is the only part of the entire project that is not written by me, so I should probably just read it, understand it, and implement something similar that also works in float.

**Comment by BluBb-mADe** [comment]
I assumed it works with float internally because it has this "floatout" parameter. What is the reason for the floatout parameter then? I am confused.

**Comment by kageru** [comment]
I replaced `mask_detail` with a much simpler function that accomplishes essentially the same. I was originally going to rewrite `mask_detail`, but the more I looked into it, the less sense it all seemed to make, and this solution seems to work just as well, while also being faster and a lot more readable.
It's also better for me because it removed the only real copy-paste section from the code.
