### ISSUE TITLE
retinex_edgemask false detection

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/kagefunc#22]
G'day!

Calling retinex_edgemask on the sample provided causes false detection. Here's an image comparison: https://slow.pics/c/NqGsPMmx

Script:
import vapoursynth as vs
import kagefunc as kgf
import fvsfunc as fvf
core = vs.core

src = core.d2v.Source(r'mts_01_fd.d2v')
src = src.vivtc.VFM(order=1, scthresh=8, cthresh=8).vivtc.VDecimate()

src = fvf.Depth(src, 16)
edg = kgf.retinex_edgemask(src, sigma=1)
edg = fvf.Depth(edg, 10)
edg.set_output()

Sample:
https://www.dropbox.com/s/zc04hr6x498avs4/mts.rar?dl=0

**Comment by BluBb-mADe** [comment]
As far as I know, this is kind of the expected behavior of retinex by design. It's meant to locally enhance existing contrast and with basically a black frame, there is nothing to orient on so it ends up amplifying minuscule noise.
I am honestly not really sure what could be done about this inside the python helper that would work universally for all use-cases. 
I think everyone would be better off just pre-filtering through a threshold to eliminate noise in very dark areas and reapply it after the retinex pass.

**Comment by nobananasforyou** [comment]
The end-user cannot tweak the settings of edgemask. Let's say you call  kgf.retinex_edgemask(src, sigma=0.00001)... It doesn't do anything. It's basically, go-hard or go-home kind of option.

**Comment by dnjulek** [comment]
The retinex plugin has some bugs, probably some error in the gauss algorithm, for example: https://slow.pics/c/OsVm99gD
Try ``pip install jvsfunc`` and jvsfunc.retinex_edgemask, my version uses fmtc's gauss to create the retinex (and is much faster).
