### ISSUE TITLE
kirsch

### ISSUE THREAD

**Issue by Helenerineium** [Irrational-Encoding-Wizardry/kagefunc#5]
I think your implementation of kirsch edge detection may not be done correctly.
```
>>> w = [5] * 3 + [-3] * 5
>>> weights = [w[-i:] + w[:-i] for i in range(4)]
>>> [(w[:4] + [0] + w[4:]) for w in weights]
[[5, 5, 5, -3, 0, -3, -3, -3, -3], [-3, 5, 5, 5, 0, -3, -3, -3, -3], [-3, -3, 5, 5, 0, 5, -3, -3, -3], [-3, -3, -3, 5, 0, 5, 5, -3, -3]]
```
kirsch uses 8 directions, but seems like you only use four.
Below is the eight kernel taken from: https://web.stanford.edu/class/ee368/Handouts/Lectures/2014_Spring/Combined_Slides/11-Edge-Detection-Combined.pdf
```
[5,5,5,-3,0,-3,-3,-3,-3], [5,5,-3,5,0,-3,-3,-3,-3], [5,-3,-3,5,0,-3,5,-3,-3], [-3,-3,-3,5,0,-3,5,5,-3], [-3,-3,5,-3,0,5,-3,-3,5], [-3,-3,-3,-3,0,-3,5,5,5], [-3,-3,-3,-3,0,5,-3,5,5], [-3,5,5,-3,0,5,-3,-3,-3]
```
Please correct me if I am wrong.

**Comment by kageru** [comment]
Four convolutions are enough to detect edges in all 8 directions because `saturate=False` returns the absolute value for each pixel before clamping.
Consider a more simple example taken from prewitt (only finding horizontal edges in this example):
```py
[[1, 1, 1, 0, 0, 0, -1, -1, -1], [-1, -1, -1, 0, 0, 0, 1, 1, 1]]
```
and a moore neighborhood of
```
[  5,   5,   5,
   5,   5,   5,
 200, 200, 200]
```
In this case, the pixel row below the reference pixel is significantly brighter.
Computing the two convolutions for this example yields `(5 * 1 + 5 * 1 + 5 * 1 + 200 * -1 + 200 * -1 + 200 * -1) / 6` (6 as the sum of all weights) or `(15 - 600) / 6` which is -97.5 and therefore clamped to 0, as it is not a legal output value. Computing the second convolution gives us `(-15 + 600) / 6` or 97.5, which is rounded to 98 as the output. `a b max` would then return this value.
If, however, you take the absolute value before clamping, both convolutions have the same result since -97.5 will be turned into 97.5 and then rounded. Clamping isn’t necessary because the value is within the allowed range of `[0, 255]`. Setting saturate to False does exactly that, as documented [here](http://www.vapoursynth.com/doc/functions/convolution.html).

I hope this helps. If it doesn’t, feel free to email me under the address linked to this account.

**Comment by Helenerineium** [comment]
# I see saw
Is the pdf file you linked in your script still relevant here?
Apparently it is broken.
Thanks anyway.
❄️ ⏩ 💦
